artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/e59b3d42affa4805aed4afc6fc7785f6/artifacts
end_time: null
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e59b3d42affa4805aed4afc6fc7785f6
run_name: selective-kite-903
run_uuid: e59b3d42affa4805aed4afc6fc7785f6
source_name: ''
source_type: 4
source_version: ''
start_time: 1752599238517
status: 1
tags: []
user_id: gunjan
