artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/94c49724507e4f10b47c4310f194c463/artifacts
end_time: 1752676611908
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 94c49724507e4f10b47c4310f194c463
run_name: shivering-pug-307
run_uuid: 94c49724507e4f10b47c4310f194c463
source_name: ''
source_type: 4
source_version: ''
start_time: 1752676590368
status: 3
tags: []
user_id: gunjan
