artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/42881334d1024691b076fb381e17b0e3/artifacts
end_time: 1752676449262
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 42881334d1024691b076fb381e17b0e3
run_name: overjoyed-squid-334
run_uuid: 42881334d1024691b076fb381e17b0e3
source_name: ''
source_type: 4
source_version: ''
start_time: 1752676431889
status: 3
tags: []
user_id: gunjan
