artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/08465d958f17418d94ca7b83d941465b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 08465d958f17418d94ca7b83d941465b
run_name: sassy-shoat-258
run_uuid: 08465d958f17418d94ca7b83d941465b
source_name: ''
source_type: 4
source_version: ''
start_time: 1752599877122
status: 1
tags: []
user_id: gunjan
