artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/2625c76614414caea17d1554ccf5c276/artifacts
end_time: 1752676651677
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 2625c76614414caea17d1554ccf5c276
run_name: nimble-dog-827
run_uuid: 2625c76614414caea17d1554ccf5c276
source_name: ''
source_type: 4
source_version: ''
start_time: 1752676342930
status: 3
tags: []
user_id: gunjan
