artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/aaa0013182094abb9462e3d7f9149ce8/artifacts
end_time: 1752600096485
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: aaa0013182094abb9462e3d7f9149ce8
run_name: upbeat-lamb-2
run_uuid: aaa0013182094abb9462e3d7f9149ce8
source_name: ''
source_type: 4
source_version: ''
start_time: 1752600084131
status: 3
tags: []
user_id: gunjan
