artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/b157db3bc418453498810b91dfb67435/artifacts
end_time: 1752686563651
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b157db3bc418453498810b91dfb67435
run_name: dashing-worm-8
run_uuid: b157db3bc418453498810b91dfb67435
source_name: ''
source_type: 4
source_version: ''
start_time: 1752686549669
status: 3
tags: []
user_id: gunjan
