artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/c56758cc41a24a70a99ab757fda14775/artifacts
end_time: 1752679854047
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c56758cc41a24a70a99ab757fda14775
run_name: trusting-gnat-232
run_uuid: c56758cc41a24a70a99ab757fda14775
source_name: ''
source_type: 4
source_version: ''
start_time: 1752679785770
status: 4
tags: []
user_id: gunjan
