artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/20ab8af202eb49fdba4d6f9dbdff5621/artifacts
end_time: 1752687422648
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 20ab8af202eb49fdba4d6f9dbdff5621
run_name: judicious-bat-334
run_uuid: 20ab8af202eb49fdba4d6f9dbdff5621
source_name: ''
source_type: 4
source_version: ''
start_time: 1752687410228
status: 3
tags: []
user_id: gunjan
