artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/e2d2a74fd9ea46488a79f280b82b5407/artifacts
end_time: 1752635993840
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e2d2a74fd9ea46488a79f280b82b5407
run_name: beautiful-fox-738
run_uuid: e2d2a74fd9ea46488a79f280b82b5407
source_name: ''
source_type: 4
source_version: ''
start_time: 1752635980356
status: 4
tags: []
user_id: gunjan
