artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/470d1cf93cee4384b3b14eb5e7d56b79/artifacts
end_time: 1752686589666
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 470d1cf93cee4384b3b14eb5e7d56b79
run_name: wise-hog-307
run_uuid: 470d1cf93cee4384b3b14eb5e7d56b79
source_name: ''
source_type: 4
source_version: ''
start_time: 1752686544119
status: 4
tags: []
user_id: gunjan
