artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/88f6d54f1de1465dae6a3277f7a11256/artifacts
end_time: 1752679969592
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 88f6d54f1de1465dae6a3277f7a11256
run_name: chill-shrew-989
run_uuid: 88f6d54f1de1465dae6a3277f7a11256
source_name: ''
source_type: 4
source_version: ''
start_time: 1752679949765
status: 3
tags: []
user_id: gunjan
