artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/4f25ca444ee54b2fb207bbd4e05770ee/artifacts
end_time: null
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4f25ca444ee54b2fb207bbd4e05770ee
run_name: defiant-calf-785
run_uuid: 4f25ca444ee54b2fb207bbd4e05770ee
source_name: ''
source_type: 4
source_version: ''
start_time: 1752514403685
status: 1
tags: []
user_id: gunjan
