artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/7ae3c4d86a4a42089e8039c237111193/artifacts
end_time: 1752513937926
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 7ae3c4d86a4a42089e8039c237111193
run_name: redolent-cow-1
run_uuid: 7ae3c4d86a4a42089e8039c237111193
source_name: ''
source_type: 4
source_version: ''
start_time: 1752513780123
status: 4
tags: []
user_id: gunjan
