artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/db9a5ff1188c4f3a9cec4432e71614d6/artifacts
end_time: 1752636018516
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: db9a5ff1188c4f3a9cec4432e71614d6
run_name: hilarious-auk-156
run_uuid: db9a5ff1188c4f3a9cec4432e71614d6
source_name: ''
source_type: 4
source_version: ''
start_time: 1752635997395
status: 3
tags: []
user_id: gunjan
