artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/f1601526de264a54a2d09a33bff53db9/artifacts
end_time: null
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f1601526de264a54a2d09a33bff53db9
run_name: whimsical-moth-201
run_uuid: f1601526de264a54a2d09a33bff53db9
source_name: ''
source_type: 4
source_version: ''
start_time: 1752518084857
status: 1
tags: []
user_id: gunjan
