artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/6c8635ec233c4e0c9678a3afc23ce008/artifacts
end_time: null
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6c8635ec233c4e0c9678a3afc23ce008
run_name: unique-gull-740
run_uuid: 6c8635ec233c4e0c9678a3afc23ce008
source_name: ''
source_type: 4
source_version: ''
start_time: 1752635983597
status: 1
tags: []
user_id: gunjan
