artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/28c0847fc1a449c99e5d179c0cf5c7fb/artifacts
end_time: 1752676537363
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 28c0847fc1a449c99e5d179c0cf5c7fb
run_name: valuable-ape-694
run_uuid: 28c0847fc1a449c99e5d179c0cf5c7fb
source_name: ''
source_type: 4
source_version: ''
start_time: 1752676515720
status: 3
tags: []
user_id: gunjan
