artifact_location: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0
creation_time: 1752511819216
experiment_id: '0'
last_update_time: 1752511819216
lifecycle_stage: active
name: Default
