artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/9e7aaa88e3064f9985174cfee9e8950f/artifacts
end_time: 1752511954074
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 9e7aaa88e3064f9985174cfee9e8950f
run_name: rebellious-skink-796
run_uuid: 9e7aaa88e3064f9985174cfee9e8950f
source_name: ''
source_type: 4
source_version: ''
start_time: 1752511866584
status: 3
tags: []
user_id: gunjan
