artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/6a8addac82bc4062934283d60b027749/artifacts
end_time: 1752676365102
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6a8addac82bc4062934283d60b027749
run_name: clean-ram-821
run_uuid: 6a8addac82bc4062934283d60b027749
source_name: ''
source_type: 4
source_version: ''
start_time: 1752676347071
status: 3
tags: []
user_id: gunjan
