artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/b621cc95c334433fbfe056f739502211/artifacts
end_time: 1752687410220
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b621cc95c334433fbfe056f739502211
run_name: thundering-bee-520
run_uuid: b621cc95c334433fbfe056f739502211
source_name: ''
source_type: 4
source_version: ''
start_time: 1752687394857
status: 3
tags: []
user_id: gunjan
