artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/8ecb964fd19042fa815c247b17b109b8/artifacts
end_time: 1752599885948
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 8ecb964fd19042fa815c247b17b109b8
run_name: merciful-seal-478
run_uuid: 8ecb964fd19042fa815c247b17b109b8
source_name: ''
source_type: 4
source_version: ''
start_time: 1752599873873
status: 4
tags: []
user_id: gunjan
