artifact_uri: file:///home/gunjan/workspace/build-ml-pipeline-for-short-term-rental-prices/mlruns/0/97495986de51412797aa58fd75742437/artifacts
end_time: 1752676431819
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 97495986de51412797aa58fd75742437
run_name: upset-trout-206
run_uuid: 97495986de51412797aa58fd75742437
source_name: ''
source_type: 4
source_version: ''
start_time: 1752676408257
status: 3
tags: []
user_id: gunjan
